# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OuSuisJe
                                 A QGIS plugin
 Retourner le coordonnée du point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-14
        copyright            : (C) 2025 by Maminiaina Indrafo
        email                : maminiainaindrafo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OuSuisJe class from file OuSuisJe.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ousuisje import OuSuisJe
    return OuSuisJe(iface)
